#pragma once
//
// pins.h — the cabinet's wiring, and the only place it is written down.
//
// These values describe the REAL machine at the lab. If you change one here,
// you are saying the physical wiring changed, and everyone gets your change.
//
// Testing on your own breadboard with different pins? Do NOT edit this file.
// Copy pins.local.example.h to pins.local.h and override there. That file is
// gitignored, so your bench setup can never break the cabinet for everyone
// else, and CI always builds the real machine.
//

#if __has_include("pins.local.h")
  #include "pins.local.h"
#endif

// --- Stepper 1 (track 1) -----------------------------------------------
#ifndef STEP_PIN1
  #define STEP_PIN1   3
#endif
#ifndef DIR_PIN1
  #define DIR_PIN1    2
#endif
#ifndef ENBL_PIN1
  #define ENBL_PIN1   7
#endif

// --- Stepper 2 (track 2) -----------------------------------------------
#ifndef STEP_PIN2
  #define STEP_PIN2   9
#endif
#ifndef DIR_PIN2
  #define DIR_PIN2    8
#endif
#ifndef ENBL_PIN2
  #define ENBL_PIN2   13
#endif

// --- Pressure plates (analog) ------------------------------------------
#ifndef PRES1
  #define PRES1       A0
#endif
#ifndef PRES2
  #define PRES2       A1
#endif

// --- Limit switches ----------------------------------------------------
#ifndef TRK1_LS1
  #define TRK1_LS1    25   // track 1 start
#endif
#ifndef TRK1_LS2
  #define TRK1_LS2    23   // track 1 end
#endif
#ifndef TRK2_LS1
  #define TRK2_LS1    29   // track 2 start
#endif
#ifndef TRK2_LS2
  #define TRK2_LS2    27   // track 2 end
#endif

// --- Buttons and indicator LEDs ----------------------------------------
#ifndef STRT_PIN
  #define STRT_PIN    48
#endif
#ifndef START_LED
  #define START_LED   53
#endif
#ifndef LED1
  #define LED1        45
#endif
#ifndef LED2
  #define LED2        37
#endif

// --- Addressable strip -------------------------------------------------
#ifndef DATA_PIN
  #define DATA_PIN    6    // WS2812B data line
#endif

// --- V2 additions ------------------------------------------------------
// The 5-button UI panel and LCD are not wired yet. Add them here with a
// #ifndef guard when the panel exists, and update hardware/wiring/ to match.
