#pragma once
//
// pins.h — the cabinet's wiring, and the only place it is written down.
//
// These values describe the REAL machine at the lab. If you change one here,
// you are saying the physical wiring changed, and everyone gets your change.
//
// Testing on your own breadboard with different pins? Do NOT edit this file.
// Copy pins.local.example.h to pins.local.h and override there. That file is
// gitignored, so your bench setup can never break the cabinet for everyone
// else, and CI always builds the real machine.
//

#include <Arduino.h>   // A0/A1 are defined here -- do not rely on the .ino
                       // having included it first; a header under src/ that
                       // includes pins.h before Arduino.h would not compile.

#if __has_include("pins.local.h")
  #include "pins.local.h"
#endif

// --- Stepper 1 (track 1) -----------------------------------------------
#ifndef STEP_PIN1
  #define STEP_PIN1   3
#endif
#ifndef DIR_PIN1
  #define DIR_PIN1    2
#endif
#ifndef ENBL_PIN1
  #define ENBL_PIN1   7
#endif

// --- Stepper 2 (track 2) -----------------------------------------------
#ifndef STEP_PIN2
  #define STEP_PIN2   9
#endif
#ifndef DIR_PIN2
  #define DIR_PIN2    8
#endif
// ⚠ Pin 13 is the Mega's built-in LED pin. The bootloader toggles it for about
// a second on every reset and every upload, and enable is active-LOW, so driver
// 2 gets spurious enable pulses at power-up and at every flash. The onboard LED
// also loads the line. This is V1's wiring, documented as-is -- moving it is a
// hardware change. See docs/HARDWARE.md.
#ifndef ENBL_PIN2
  #define ENBL_PIN2   13
#endif

// --- Pressure plates (analog) ------------------------------------------
#ifndef PRES1
  #define PRES1       A0
#endif
#ifndef PRES2
  #define PRES2       A1
#endif

// --- Limit switches ----------------------------------------------------
#ifndef TRK1_LS1
  #define TRK1_LS1    25   // track 1 start
#endif
#ifndef TRK1_LS2
  #define TRK1_LS2    23   // track 1 end
#endif
#ifndef TRK2_LS1
  #define TRK2_LS1    29   // track 2 start
#endif
#ifndef TRK2_LS2
  #define TRK2_LS2    27   // track 2 end
#endif

// --- Buttons and indicator LEDs ----------------------------------------
#ifndef STRT_PIN
  #define STRT_PIN    48
#endif
#ifndef START_LED
  #define START_LED   53
#endif
#ifndef LED1
  #define LED1        45
#endif
#ifndef LED2
  #define LED2        37
#endif

// --- Addressable strip -------------------------------------------------
#ifndef DATA_PIN
  #define DATA_PIN    6    // WS2812B data line
#endif

// --- V2: the 5-button UI panel and LCD ---------------------------------
// Assigned 2026-09-02 from the team's wiring table. Reasoning, and the three
// problems found in that table, are in docs/decisions/0002-ui-panel-wiring.md.
//
// ⚠ NOT WIRED YET. These are the intended assignments, not the cabinet as it
// stands. Nothing in the firmware uses them until the menu lands.

// HD44780 parallel LCD, 4-bit mode.
// ⚠ The module's pin numbers and the Arduino's pin numbers are different things.
// LCD_D6 below is Arduino pin 34, going to *module* pin 13. Do not wire a data
// line to Arduino pin 13 -- that is the built-in LED, and it is ENBL_PIN2.
#ifndef LCD_RS
  #define LCD_RS      30   // -> module pin 4
#endif
#ifndef LCD_EN
  #define LCD_EN      31   // -> module pin 6
#endif
#ifndef LCD_D4
  #define LCD_D4      32   // -> module pin 11  (missing from the team's table)
#endif
#ifndef LCD_D5
  #define LCD_D5      33   // -> module pin 12
#endif
#ifndef LCD_D6
  #define LCD_D6      34   // -> module pin 13
#endif
#ifndef LCD_D7
  #define LCD_D7      35   // -> module pin 14
#endif

// Five UI buttons, INPUT_PULLUP, other leg to GND.
#ifndef BTN_UP
  #define BTN_UP      40
#endif
#ifndef BTN_DOWN
  #define BTN_DOWN    41
#endif
#ifndef BTN_SELECT
  #define BTN_SELECT  42
#endif
#ifndef BTN_BACK
  #define BTN_BACK    43
#endif
#ifndef BTN_START
  #define BTN_START   44   // duplicates STRT_PIN 48 during the transition
#endif
